### ISSUE TITLE
Make map markers and info windows globally accessible

### ISSUE THREAD

**Issue by wpscholar** [wpscholar/stellar-places#11]
@mgratch Currently, the Google map and map bounds can be obtained directly from jQuery.data() on the map in the DOM. However, markers and infoWindows cannot be accessed at all.  In order to make it easier for customizations to be made, I propose the following:

On the Google Map object, let's add a 'markers' property which is an array of markers added to the map.  For each marker object, let's add an 'infoWindow' property which contains the infoWindow for that marker.  This way, external scripts can access and easily integrate with Google Maps created by Stellar Places.

Example of infoWindow being attached to a marker: http://stackoverflow.com/questions/3158598/google-maps-api-v3-adding-an-infowindow-to-each-marker

**Comment by mgratch** [comment]
see https://github.com/wpscholar/stellar-places/pull/12

**Comment by wpscholar** [comment]
Thanks @mgratch !  Code merged.  See note on pull request #12 regarding some additional tweaks I made.
